<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>KickBase.Api</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\KickBase.Analyzers\KickBase.Analyzers.csproj">
                        <OutputItemType>Analyzer</OutputItemType>
                        <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
                        <GlobalAnalyzer>true</GlobalAnalyzer>
      </ProjectReference>
        <ProjectReference Include="..\KickBase.Analyzers.CodeFixes\KickBase.Analyzers.CodeFixes.csproj">
        <OutputItemType>Analyzer</OutputItemType>
        <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
      <ProjectReference Include="..\KickBase.Domain\KickBase.Domain.csproj" />
    </ItemGroup>
</Project>
