<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>KickBase.Export</RootNamespace>
      <UserSecretsId>e4da813e-76c3-4d38-9aa2-b59e8e8ad194</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CsvHelper" Version="33.1.0" />
      <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Kickbase.Api\KickBase.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="appsettings.json" />
      <Content Include="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
